### ISSUE TITLE
新生课程任务清单

### ISSUE THREAD

**Issue by lxx2013** [DML308/student-camp-2018#7]
以
```
- [ ] `2018-11-xx 00:00:00`  xx考试  
- [ ] `2018-11-xx 00:00:00`  大作业(报告) 时间
- [ ] `2018-11-xx 00:00:00`  大作业(代码+报告) 
```
的格式渲染为:
- [ ] `2018-11-xx 00:00:00`  xx考试  
- [ ] `2018-11-xx 00:00:00`  xx课上台 PPT 演示 
- [ ] `2018-11-xx 00:00:00`  xx课程结课报告 
- [ ] `2018-11-xx 00:00:00`  xx课程作业(代码+报告) 

也可以用表格格式.

列出任务有利于大家互相了解学习情况合理分配其它任务, 以及提醒自己别错过考试.

**Comment by yaerlan** [comment]
### 任务清单
- [ ] `2018-11-30 24:00:00`  病毒学报告
- [ ] `2018-11-30 24:00:00`  软件工程报告（group work）
- [ ] `2018-11-22 18:30:00` 党课培训
- [ ] `2018-11-?    24:00:00` 党员转正大会

### 其他任务
• 矩阵论复习（15周结课）考试时间未定
• 分布式课程（17周结课）无考试 提交报告
• 多媒体课程（17周结课）考试时间未定（开卷）
• 高级计算机系统结构课（17周结课）考试时间未定（开卷）

**Comment by GalaxyYan** [comment]
日期|任务
-|-
2018.11.30|病毒学报告
2018.11.30|项目管理报告
2018.12.07|人工智能报告
2018.12.xx|矩阵论考试、计算机体系结构考试、流媒体报告...

**Comment by Zpadger** [comment]
- [ ] `2018-11-30 00:00:00`  计算机系统分析与性能评价结课论文（英文）  
- [ ] `2018-11-30 00:00:00`  计算机病毒模型报告
- [ ] `2018-12-15 00:00:00`  英语六级考试
- [ ] `2018-12-18 00:00:00`  流媒体技术考试（开卷+编程写代码）
- [ ] `2018-12-xx 00:00:00`  矩阵论考试（时间待定）
- [ ] `2018-12-xx 00:00:00`  高级计算机系统结构考试（时间待定）
- [ ] `2018-12-xx 00:00:00`  流媒体技术考试（时间待定）

**Comment by zzNire** [comment]
- [ ] `2018-11-xx 00:00:00`  应用数学 （未结课）
- [ ] `2018-11-xx 00:00:00` 分布式系统与中间件 （未知）
- [ ] `2018-11-xx 00:00:00`   Hadoop （已上交项目）
- [ ] `2018-11-xx 00:00:00` 多媒体技术 （未结课）
- [ ] `2018-11-xx 00:00:00`   中国特色社会主义理论 （未知）
